version: "1.0"
server:
  listen: ":2906"
storage:
  runtime:
    type: "memory"
llm_providers:
  - id: "dummy"
    type: "openai"
    api_keys: ["dummy"]
    model: "gpt-4o"
api_keys:
  - key: "test-12"
    allowed_providers: ["*"]
policy:
  cache:
    enabled: false