version: "1.0"

server:
  listen: ":2906"

llm_providers:
  - id: "openai"
    type: "openai"
    api_keys: ["dummy"]
    model: "gpt-4o"
    pricing:
      input_token_cost: 0.002
      output_token_cost: 0.01
    limits:
      req_per_min: 200
      tokens_per_min: 100000

api_keys:
  - key: "test-12"
    allowed_providers: ["*"]
    description: "Test API key"

model_aliases:
  gpt-4o: openai:gpt-4o

policy:
  cache:
    enabled: true
    ttl_seconds: 10